export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"博客首页","i":"home"},["/README.md"]],
  ["v-184f4da6","/intro.html",{"d":1695882610000,"v":"/assets/images/cover3.jpg","e":"<h1> 介绍页</h1>\n<p>将你的个人介绍和档案放置在此处。</p>\n","r":{"minutes":0.08,"words":23},"y":"a","t":"介绍页","i":"circle-info"},[":md"]],
  ["v-14e6501c","/link/",{"d":1696909682000,"c":"网站","u":999,"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/thomas-blog/link/front-end-tools.html\" target=\"blank\">前端工具网站</a></p>\n</li>\n<li>\n<p><a href=\"/thomas-blog/link/front-end-learn.html\" target=\"blank\">前端学习网站</a></p>\n</li>\n<li>\n<p><a href=\"/thomas-blog/link/other-link.html\" target=\"blank\">其他好用网站</a></p>\n</li>\n</ul>\n","r":{"minutes":0.15,"words":46},"y":"a","t":"好用的网站合集","i":"laptop-code"},["/link/README.md"]],
  ["v-d17748f2","/link/front-end-learn.html",{"y":"p","t":"前端学习网站合集"},[":md"]],
  ["v-7daf8650","/link/front-end-tools.html",{"y":"p","t":"前端好用工具的网站合集"},[":md"]],
  ["v-1bcf3f06","/link/other-link.html",{"y":"p","t":"令你工作事半功倍的网站合集"},[":md"]],
  ["v-1473bf53","/demo/",{"d":1695882610000,"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/thomas-blog/demo/markdown.html\" target=\"blank\">Markdown 展示</a></p>\n</li>\n<li>\n<p><a href=\"/thomas-blog/demo/page.html\" target=\"blank\">页面展示</a></p>\n</li>\n<li>\n<p><a href=\"/thomas-blog/demo/disable.html\" target=\"blank\">禁用展示</a></p>\n</li>\n<li>\n<p><a href=\"/thomas-blog/demo/encrypt.html\" target=\"blank\">加密展示</a></p>\n</li>\n</ul>","r":{"minutes":0.14,"words":41},"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"d":1695882610000,"c":["使用指南"],"g":["禁用"],"e":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","r":{"minutes":0.43,"words":128},"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"d":1695882610000,"c":["使用指南"],"g":["Markdown"],"e":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","r":{"minutes":3.43,"words":1030},"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"a":"Thomas.wang","d":1577836800000,"l":"2020年1月1日","c":["使用指南"],"g":["页面配置","使用指南"],"u":true,"v":"/assets/images/cover1.jpg","e":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","r":{"minutes":1.47,"words":441},"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-5e41dbce","/category/%E7%BD%91%E7%AB%99/",{"y":"p","t":"网站 分类","I":0},["/category/网站/"]],
  ["v-83e1f92e","/tag/%E7%A6%81%E7%94%A8/",{"y":"p","t":"标签: 禁用","I":0},["/tag/禁用/"]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 分类","I":0},["/category/使用指南/"]],
  ["v-484552dc","/tag/markdown/",{"y":"p","t":"标签: Markdown","I":0},[]],
  ["v-a378ad66","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/",{"y":"p","t":"标签: 页面配置","I":0},["/tag/页面配置/"]],
  ["v-7b167472","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"标签: 使用指南","I":0},["/tag/使用指南/"]],
]
